---

- name: Get Home directory of restic_user
  ansible.builtin.getent:
    database: passwd
    key: "{{ restic_user }}"
    split: ":"

- name: Set rclone config directory
  ansible.builtin.set_fact:
    rclone_conf_dir: "{{ getent_passwd[restic_user][4] + rclone_config_dir }}"

- name: Create rclone config
  ansible.builtin.file:
    path: "{{ rclone_conf_dir }}"
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: '0750'

- name: Copy rclone configuration
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: '0644'
  with_items:
    - template: rclone.conf.j2
      dest: "{{ rclone_conf_dir }}/rclone.conf"
