---
- name: Create the restic server systemd config
  ansible.builtin.template:
    src: restic-backup.service.j2
    dest: "/etc/systemd/system/restic-backup.service"
    owner: root
    group: root
    mode: '0644'
  notify: systemd reload

- name: Add systemd timer for restic
  ansible.builtin.template:
    src: restic-backup.timer.j2
    dest: /etc/systemd/system/restic-backup.timer
    owner: root
    group: root
    mode: '0644'
  notify: systemd reload

- name: Enable and start restic timer
  ansible.builtin.systemd:
    name: restic-backup.timer
    enabled: true
    state: started
