---
- name: Check if restic is installed
  stat:
    path: '{{ restic_path }}'
  register: restic_binary

- name: Install restic
  include_tasks: install_restic.yml
  when: not restic_binary.stat.exists or restic_force_install

- name: Check if rclone is installed
  stat:
    path: '{{ rclone_path }}'
  register: rclone_binary

- name: Install gclone
  include_tasks: install_rclone.yml
  when: not rclone_binary.stat.exists and rclone_install

- name: Configure restic backup
  include_tasks: configure_restic.yml

- name: Install restic systemd backup service
  include_tasks: install_restic_backup_service.yml

- name: Install restic systemd clean service
  include_tasks: install_restic_clean_service.yml
  when: restic_clean_service
