---
- name: Converge | Create Minio server
  hosts: minio
  become: true
  gather_facts: true
  vars:
    server_hostname: minio.picluster.ricsanfre.com
    ssl_key_size: 4096
    ssl_certificate_provider: selfsigned
    key_type: RSA
    country_name: ES
    email_address: admin@ricsanfre.com
    organization_name: Ricsanfre

  pre_tasks:
    - name: Generate custom CA
      include_tasks: tasks/generate_custom_ca.yml
      args:
        apply:
          delegate_to: localhost
          become: false
    - name: Generate customCA-signed SSL certificates for minio
      include_tasks: tasks/generate_ca_signed_cert.yml
      args:
        apply:
          delegate_to: localhost
          become: false
    - name: Load tls key and cert
      set_fact:
        minio_key: "{{ lookup('file','certificates/' + server_hostname + '.key') }}"
        minio_cert: "{{ lookup('file','certificates/' + server_hostname + '.pem') }}"

  roles:
    - role: ricsanfre.minio
      minio_root_user: "miniadmin"
      minio_root_password: "supers1cret0"
      minio_enable_tls: true
      minio_validate_certificate: false
      minio_buckets:
        - name: restic
          policy: read-write
      minio_users:
        - name: restic
          password: supers1cret0
          buckets_acl:
            - name: restic
              policy: read-write

- name: Converge | Configure backup
  hosts: server
  become: true
  gather_facts: true
  roles:
    - role: ricsanfre.backup
      restic_repository: "s3:https://10.11.0.1:9091/restic"
      restic_aws_access_key_id: restic
      restic_aws_secret_access_key: supers1cret0
      restic_ca_cert: ""
